export enum EusersActionTypes {
  LOGIN_USER = "LOGIN_USER",
  LOGOUT_USER = "LOGOUT_USER",
  SET_USER_INSTAGRAM_PICTURES = "SET_USER_INSTAGRAM_PICTURES",
  SAVE_USER_DATA = "SAVE_USER_DATA",
  UPDATE_USER_DATA = "UPDATE_USER_DATA",
}
